### PR TITLE
Managed Identity

### LINKED ISSUE #204: Managed Identity?
Does this support managed identities like in visual studio?
Have another user running 19.1 and we have managed identities configured for our DBs and in VS it just auth uses our normal creds.  Im not sure if because on my machine i have VS 2019 and Rider its using the token from VS, but on the other persons its not.

Error:
```
 Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net/, Authority: . Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.

[5/21/2019 4:35:54 PM] Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net/, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Visual Studio Token

provider file not found at "C:\Users\USERNAME\AppData\Local\.IdentityService\AzureServiceAuth\tokenprovider.json"

[5/21/2019 4:35:54 PM] Parameters: Connection String: [No connection string specified], Resource: https://database.windows.net/, Authority: . Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. 'az' is not recognized as an internal or external command,
```

### PR DESCRIPTION
**Pull request by maartenba**
Fixes #204 (can be merged after upstream is merged in)

Not authenticated with Azure CLI?
image

Authenticated with Azure CLI:
image

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/managedidentity/AzureManagedIdentityConfigurationPanel.kt [hunk 1]
```diff
@@ -0,0 +1,114 @@
...
+import com.microsoft.azuretools.authmanage.AuthMethodManager
+import com.microsoft.azuretools.ijidea.actions.AzureSignInAction
+import com.microsoft.intellij.configuration.ui.AzureRiderAbstractConfigurablePanel
+import org.jetbrains.plugins.azure.RiderAzureBundle
+
+
+@Suppress("UNUSED_LAMBDA_EXPRESSION")
+class AzureManagedIdentityConfigurationPanel(private val project: Project) : AzureRiderAbstractConfigurablePanel {
+
+    private val disposable = Disposer.newDisposable()
```
Comment (sdubov) [inline PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/managedidentity/AzureManagedIdentityConfigurationPanel.kt]: Why do you need this disposable?

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/managedidentity/AzureManagedIdentityConfigurationPanel.kt [hunk 2]
```diff
@@ -0,0 +1,114 @@
...
+                    row {
+                        button(RiderAzureBundle.message("settings.managedidentity.sign_in_with_cli")) {
+                            try {
+                                AuthMethodManager.getInstance().signOut()
+                                if (AzureSignInAction.doSignIn(AuthMethodManager.getInstance(), project)) {
+                                    rowConfiguredCorrectly.visible = true
+                                    rowRequiresSignIn.subRowsVisible = false
+                                }
+                            } catch (e: Exception) {
+                                e.printStackTrace()
```
Comment (sdubov) [inline PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/managedidentity/AzureManagedIdentityConfigurationPanel.kt]: Can we initialise logger and print some readable error here?

**Comment by sdubov** [comment]
Discussed this panel with ilya.aleksandrov from Rider UX team. He suggested to rework the presentation to use the following pattern:
```
<describe the problem>, e.g. "Azure Cloud Shell feature will be disabled when not logged in using Azure CLI."
<show a button to login if needed or OK status>
<link to details: how does Azure authentication works>. This link interrupt from reading the panel
```

**Review by sdubov — APPROVED** [review]
