### PR TITLE
Surface Better Error Messages When Auth Fails

### LINKED ISSUE #438: Better error messages when auth fails
When calling the `SubscriptionManager.updateAccountSubscriptionList` method, there is a chance that the call to Azure could fail with a few error codes.

These error codes and messages can be surfaced to help users make a decision as to what to do next.

### In Rider

image

### In The Logs

image

### LINKED ISSUE #452: Device login - Subscription lookup improvements
When using device login, fetching subscriptions fails if there is a tenant you don't have access to.
The error can be shown in the error log, but ideally subscription selection should be possible for tenants you do have access to.

Relates to #438

### PR DESCRIPTION
**Pull request by maartenba**
Fixes #438
Fixes #452
Upstream fix https://github.com/microsoft/azure-tools-for-java/pull/4991

This PR shows more detailed error messages, and makes the experience a bit nicer when a token is no longer valid.

@sdubov we discussed showing the login form when the latter happens, but for now decided to not do that yet (not forcing a modal dialog onto people)

### CODE REVIEW

File: Utils/azuretools-core/src/com/microsoft/azuretools/authmanage/AuthExceptionUtil.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+    /**
+     * When a Throwable is an AuthException that requires the user to re-authenticate,
+     * such as the one described in https://github.com/JetBrains/azure-tools-for-intellij/issues/438,
+     * returns the AuthException.
+     *
+     * @param throwable Throwable to check.
+     * @return When a Throwable is an AuthException that requires the user to re-authenticate, returns the AuthException. Returns null otherwise.
+     */
+    public static AuthException GetUserRetryableAuthException(Throwable throwable) {
```
Comment (lillieMaiBauer) [inline Utils/azuretools-core/src/com/microsoft/azuretools/authmanage/AuthExceptionUtil.java]: I detect that this code is problematic. According to the [Bad practice (BAD_PRACTICE)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#bad-practice-bad-practice), [Nm: Method names should start with a lower case letter (NM_METHOD_NAMING_CONVENTION)](https://spotbugs.readthedocs.io/en/stable/bugDescriptions.html#nm-method-names-should-start-with-a-lower-case-letter-nm-method-naming-convention).
Methods should be verbs, in mixed case with the first letter lowercase, with the first letter of each internal word capitalized.

**Review by sdubov — APPROVED** [review]
