### PR TITLE
[Azure Functions] Isolated workers improvements

### LINKED ISSUE #491: Azure Functions - Isolated Worker - Better handle host startup error
Right now if an error occurs during startup, we wait for the full timeout before showing a result (as we wait for `<PID>`). This should be handled better: if startup fails, show console and stop debugging.

### PR DESCRIPTION
**Pull request by maartenba**
Fixes #491

* Show progress bar while starting functions host
* Display console on failure

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt [hunk 1]
```diff
@@ -66,26 +74,30 @@ class AzureFunctionsDotNetCoreIsolatedDebugProfile(
         // Launch Azure Functions host process
         launchAzureFunctionsHost()
 
+        // Show progress bar
+        ProgressManager.getInstance().run(
```
Comment (sdubov) [inline PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt:78]: This construction looks pretty unusual from my view - you run a coroutine that start a fake background activity just to show a progress. Why not to put all your logic inside this background activity, so, you do not need to handle progress separately from an actual activity?

Comment (maartenba) [reply PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreIsolatedDebugProfile.kt:78]: Agree. Do you know if we can block execution of the `createWorkerRunInfo` method in this background activity? (like `pumpMessages` does now)

**Review by sdubov — APPROVED** [review]
