### PR TITLE
[Rider] AppService SCM endpoint is not right when use azure chinaenvironment

### LINKED ISSUE #212: [Rider] AppService SCM endpoint is not right when use azure chinaenvironment
I am using the Azure china environment. after changing AzureToolsForIntelliJ/AadProvider.json to  Environment China. 
``` json
{
"EnvironmentName": "CHINA"
}
```
The china account can log in through rider, but I still cannot publish my asp.net core project to azure china's app service, the SCM endpoint is not right

`
Publishing ZIP file. Attempt 1 of 3...
Fail publishing ZIP file: java.net.ConnectException: Failed to connect to xxxxx.scm.azurewebsites.net/xxx.xxx.xxx.xxx:443
`

Except : xxxxx.scm.chinacloudsites.cn

Actual : xxxxx.scm.azurewebsites.net

### PR DESCRIPTION
**Pull request by maartenba**
Fixes #212

### CODE REVIEW

**Comment by maartenba** [comment]
@sdubov can you check?

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/runstate/FunctionAppDeployStateUtil.kt [hunk 1]
```diff
@@ -156,7 +156,11 @@ object FunctionAppDeployStateUtil {
 
             functionAppStop(app, processHandler)
 
-            KuduClient.kuduZipDeploy(zipFile, app.publishingProfile, app.name(), processHandler)
+            val kuduBaseUrl = "https://" + app.defaultHostName().toLowerCase()
+                    .replace("http://", "")
```
Comment (sdubov) [inline PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/runstate/FunctionAppDeployStateUtil.kt]: @maartenba, why do we need this replacement? Is that a case when `app.defaultHostName()` return full name with protocol?

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/runstate/FunctionAppDeployStateUtil.kt [hunk 2]
```diff
@@ -156,7 +156,11 @@ object FunctionAppDeployStateUtil {
...
+                    .replace(app.name().toLowerCase(), app.name().toLowerCase() + ".scm")
+
+            KuduClient.kuduZipDeploy(zipFile, app.publishingProfile, app.name(), kuduBaseUrl, processHandler)
```
Comment (sdubov) [inline PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/runstate/FunctionAppDeployStateUtil.kt]: Do discuss: since we have same logic to detect a correct base name, maybe create a overrider for `kuduZipDeploy()` that will take an instance of `WebAppBase` and then make this transformation under the hood:

```
fun kuduZipDeploy(zipFile: File, app: WebAppBase, processHandler: RunProcessHandler) {
   ...
}
```

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/runstate/FunctionAppDeployStateUtil.kt (hunk 1 above)
Comment (maartenba) [reply PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/runstate/FunctionAppDeployStateUtil.kt]: Yes, that's correct.

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/runstate/FunctionAppDeployStateUtil.kt (hunk 2 above)
Comment (maartenba) [reply PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/runstate/FunctionAppDeployStateUtil.kt]: Updated.

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/helpers/deploy/KuduClient.kt [hunk 3]
```diff
@@ -46,15 +47,35 @@ object KuduClient {
...
+     * Note: Azure SDK supports a native [FunctionApp.zipDeploy(File)] method. Hoverer, we cannot use it for files with BOM
      *       Method throws an exception while reading the JSON file that contains BOM. Use our own implementation until fixed
      *
      * @param zipFile - zip file instance to be published
      * @param processHandler - a process handler to show a process message
      *
      * @throws [RuntimeException] in case REST request was not succeed or timed out after 3 attempts
      */
-    fun kuduZipDeploy(zipFile: File, publishingProfile: PublishingProfile, appName: String, processHandler: RunProcessHandler) {
+    fun kuduZipDeploy(zipFile: File, publishingProfile: PublishingProfile, appName: String, kuduWebApp: WebAppBase, processHandler: RunProcessHandler) {
```
Comment (sdubov) [inline PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/helpers/deploy/KuduClient.kt]: I think you can simplify this overload since you pass a WebAppBase object:
```
fun kuduZipDeploy(zipFile: File, app: WebAppBase, processHandler: RunProcessHandler) {
    val appName = app.name()
    val kuduBaseUrl = "https://" + app.defaultHostName().toLowerCase()
	                .replace("http://", "")
	                .replace(appName.toLowerCase(), appName.toLowerCase() + ".scm")
   
   kuduZipDeploy(zipFile, app.publishingProfile, appName, kuduBaseUrl, processHandler)
}
```

**Review by sdubov — APPROVED** [review]
