### PR TITLE
Fix #167. Fix project set for run configuration and persists during runs

### LINKED ISSUE #167: Configurations do not save/display correctly.
None of the Azure Publish settings are saving or displaying correctly. If I attempt to create a new Azure Publish configuration, I set the Name, which web app to deploy to, and which project in the solution should be published. If I open this configuration again, the project I selected is never the one chosen. The view always defaults to the first project in the list. I have published apps on top of each other as a result when I didn't notice this was happening. 

When I open rider, all of the Azure Publish profiles are invalid and I always have to edit and apply the changes again if I want to publish during the session. Saving the credentials did not resolve this. 

Additionally, sometimes when I am trying to verify the publish profiles are working correctly they will randomly rename themselves to the default value. Such as "Azure Web App: Project Name". I just had all 3 publish profiles rename to the exact same thing because they all default back to the first project in the solution. 

As long as I am very careful to work around these bugs the actual publishing to Azure works perfectly and I am very happy to have it.

### PR DESCRIPTION
**Pull request by sdubov**
- Fix the issue with setting a project for a run configuration
- Persists run configuration between application runs

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/validator/FunctionAppConfigValidator.kt [hunk 1]
```diff
@@ -57,21 +57,21 @@ object FunctionAppConfigValidator : ConfigurationValidator() {
...
+            checkStatus(FunctionAppValidator.checkFunctionAppIdIsSet(model.appId))
         }
     }
 
     /**
      * Check Connection String name existence for a web app
      *
      * @param name connection string name
-     * @param webAppId a web app to check
+     * @param app a function app to check
```
Comment (maartenba) [inline PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/validator/FunctionAppConfigValidator.kt]: XML docs do not match method signature.

**Review by maartenba — APPROVED** [review]
One really minor remark, otherwise looks good.

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/validator/FunctionAppConfigValidator.kt (hunk 1 above)
Comment (sdubov) [reply PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/com/microsoft/intellij/runner/functionapp/config/validator/FunctionAppConfigValidator.kt]: Fixed.
