### PR TITLE
Cannot debug on Windows 10 when Azure Core Tools are installed with Chocolatey

### LINKED ISSUE #478: Cannot debug on Windows 10 when Azure Core Tools are installed with Chocolatey
I can not debug Azure Functions Projects on 2 Machines with Windows 10.
On my Mac it works.
On the Windows Machines also run the project does work.
In debug mode i got the Error: 
"C:\Program Files (x86)\JetBrains\JetBrains Rider 2021.1.1\lib\ReSharperHost\JetBrains.Debugger.Worker.exe" --mode=client --frontend-port=54623 "--plugins=C:\Program Files (x86)\JetBrains\JetBrains Rider 2021.1.1\plugins\rider-unity\dotnetDebuggerWorker"
Process finished with exit code 0.One or more errors occurred.

### PR DESCRIPTION
**Pull request by maartenba**
Fixes #478

Thank you @ArsenyChernyaev for the patch!

### CODE REVIEW

File: PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreDebugProfile.kt [hunk 1]
```diff
@@ -47,12 +50,24 @@ class AzureFunctionsDotNetCoreDebugProfile(
...
+                createWorkerCmdFor(consoleKind, port, getWorkerPlatform(lifetime)).apply {
                     withWorkDirectory(dotNetExecutable.workingDirectoryOrExeFolder)
                 })
         return patchCommandLineInPlugins(lifetime, executionEnvironment.project, runInfo)
     }
 
+    private fun getWorkerPlatform(lifetime: Lifetime): DebuggerWorkerPlatform {
+        if (!SystemInfo.isWindows) return DebuggerWorkerPlatform.AnyCpu
+
+        // TODO: ClassCastException occurs with this line of code.
```
Comment (maartenba) [inline PluginsAndFeatures/azure-toolkit-for-intellij/rider/src/org/jetbrains/plugins/azure/functions/run/AzureFunctionsDotNetCoreDebugProfile.kt:62]: `Caused by: java.lang.ClassCastException: class kotlin.coroutines.jvm.internal.CompletedContinuation cannot be cast to class kotlinx.coroutines.internal.DispatchedContinuation (kotlin.coroutines.jvm.internal.CompletedContinuation and kotlinx.coroutines.internal.DispatchedContinuation are in unnamed module of loader com.intellij.util.lang.PathClassLoader @61dc03ce)`

**Review by sdubov — APPROVED** [review]
